service: lawgile-api
disabledDeprecations:
  - "*"

package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: sa-east-1

  environment:
    tableName: lawgile

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:sa-east-1:*:*"

functions:
  create:
    handler: create.main
    events:
      - http:
          path: pedidos
          method: post

  get:
    handler: get.main
    events:
      - http:
          path: pedidos/{id}
          method: get

  list:
    handler: list.main
    events:
      - http:
          path: pedidos
          method: get
